// OBS Studio WebSocket v5 monitor. A client belongs to one room: a multi-room
// campus can monitor its control rooms independently without sharing a host or
// password. Every request below is read-only.
import { createHash, randomUUID } from 'node:crypto';
import WebSocket from 'ws';
import { getObs } from '../connectivity.js';

const clients = new Map();
const TIMEOUT = 5_000;
const METERS = 1 << 16;
const NO_SIGNAL_DB = -60;
const safePreviewUrl = (value) => { try { const url = new URL(String(value ?? '')); return url.protocol === 'https:' ? url.href : null; } catch { return null; } };
const digest = (value) => createHash('sha256').update(value).digest('base64');
const offline = (cfg, error) => ({ configured: Boolean(cfg?.host), connected: false, streaming: false, recording: false, recordingPaused: false, streamDurationMs: 0, recordDurationMs: 0, activeFps: null, bitrateKbps: null, droppedFrames: 0, droppedFramesPercent: 0, droppedFramesWarning: cfg?.droppedFramesWarning ?? 0.5, programScene: null, programSources: [], audioDb: null, audioStatus: 'no-signal', primaryAudioInput: cfg?.primaryAudioInput ?? null, sourceOptions: [], cpuUsage: null, diskFreeGb: null, previewImageUrl: safePreviewUrl(cfg?.previewImageUrl), error });

class ObsClient {
  constructor(cfg) { this.cfg = cfg; this.socket = null; this.requests = new Map(); this.sources = []; this.previousBytes = null; this.delay = 1_000; this.reconnect = null; this.telemetry = null; this.generation = 0; this.current = offline(cfg, 'OBS Studio is connecting…'); }
  set(next) { this.current = { ...this.current, ...next, sourceOptions: this.sources, previewImageUrl: safePreviewUrl(this.cfg.previewImageUrl) }; }
  auth(authentication) { return authentication ? digest(`${digest(`${this.cfg.password ?? ''}${authentication.salt}`)}${authentication.challenge}`) : undefined; }
  close() { if (this.socket) { this.socket.removeAllListeners(); try { this.socket.close(); } catch {} } this.socket = null; for (const { reject, timer } of this.requests.values()) { clearTimeout(timer); reject(new Error('OBS connection closed')); } this.requests.clear(); }
  stop() { clearTimeout(this.reconnect); clearInterval(this.telemetry); this.reconnect = this.telemetry = null; this.generation += 1; this.close(); this.previousBytes = null; }
  request(requestType, requestData = {}) { const requestId = randomUUID(); return new Promise((resolve, reject) => { const timer = setTimeout(() => { this.requests.delete(requestId); reject(new Error(`OBS ${requestType} timed out`)); }, TIMEOUT); timer.unref?.(); this.requests.set(requestId, { resolve, reject, timer }); if (!this.socket || this.socket.readyState !== WebSocket.OPEN) { clearTimeout(timer); this.requests.delete(requestId); reject(new Error('OBS websocket is not connected')); return; } this.socket.send(JSON.stringify({ op: 6, d: { requestType, requestId, requestData } })); }); }
  response(data) { const pending = this.requests.get(data.requestId); if (!pending) return; this.requests.delete(data.requestId); clearTimeout(pending.timer); if (data.requestStatus?.result) pending.resolve(data.responseData ?? {}); else pending.reject(new Error(data.requestStatus?.comment || `OBS request failed (${data.requestStatus?.code ?? 'unknown'})`)); }
  meter(inputs) { const input = (this.cfg.primaryAudioInput && inputs.find((v) => v.inputName === this.cfg.primaryAudioInput)) ?? inputs[0]; if (!input) return; const values = Array.isArray(input.inputLevelsMul) ? input.inputLevelsMul.flatMap((c) => Array.isArray(c) ? c.slice(0, 2) : []) : []; const max = Math.max(...values.filter((v) => Number.isFinite(v) && v > 0)); const audioDb = Number.isFinite(max) ? Math.round(20 * Math.log10(max) * 10) / 10 : null; this.set({ primaryAudioInput: input.inputName, audioDb, audioStatus: audioDb != null && audioDb > NO_SIGNAL_DB ? 'active' : 'no-signal' }); }
  async refresh() { if (!this.current.connected) return; const [stream, record, stats, scene] = await Promise.all([this.request('GetStreamStatus'), this.request('GetRecordStatus'), this.request('GetStats'), this.request('GetCurrentProgramScene')]).catch(() => []); if (!stream || !record || !stats || !scene) return; const now = Date.now(); const bytes = Number(stream.outputBytes ?? 0); let bitrateKbps = this.current.bitrateKbps; if (this.previousBytes && now > this.previousBytes.at && bytes >= this.previousBytes.bytes) bitrateKbps = Math.round((bytes - this.previousBytes.bytes) * 8 / (now - this.previousBytes.at)); this.previousBytes = { bytes, at: now }; const droppedFrames = Number(stream.outputSkippedFrames ?? 0); const total = Number(stream.outputTotalFrames ?? 0); const programSources = await this.request('GetSceneItemList', { sceneName: scene.currentProgramSceneName }).then((v) => (v.sceneItems ?? []).map((item) => item.sourceName).filter(Boolean)).catch(() => this.current.programSources); this.set({ connected: true, error: undefined, streaming: Boolean(stream.outputActive), streamReconnecting: Boolean(stream.outputReconnecting), streamDurationMs: Number(stream.outputDuration ?? 0), recording: Boolean(record.outputActive), recordingPaused: Boolean(record.outputPaused), recordDurationMs: Number(record.outputDuration ?? 0), activeFps: Number.isFinite(Number(stats.activeFps)) ? Number(stats.activeFps) : null, bitrateKbps, droppedFrames, droppedFramesPercent: Math.round((total ? droppedFrames / total * 100 : 0) * 100) / 100, droppedFramesWarning: this.cfg.droppedFramesWarning ?? 0.5, programScene: scene.currentProgramSceneName ?? null, programSources, cpuUsage: Number.isFinite(Number(stats.cpuUsage)) ? Number(stats.cpuUsage) : null, diskFreeGb: Number.isFinite(Number(stats.availableDiskSpace)) ? Number(stats.availableDiskSpace) : null }); }
  reconnectSoon(message) { clearInterval(this.telemetry); this.telemetry = null; this.close(); this.set(offline(this.cfg, message)); if (this.reconnect) return; const delay = this.delay; this.delay = Math.min(this.delay * 2, 10_000); this.reconnect = setTimeout(() => { this.reconnect = null; this.connect(); }, delay); this.reconnect.unref?.(); }
  connect() { if (this.socket || !this.cfg.host) return; const generation = ++this.generation; let opened = false; try { this.socket = new WebSocket(`ws://${this.cfg.host}:${this.cfg.port ?? 4455}`, { handshakeTimeout: TIMEOUT }); } catch (error) { this.reconnectSoon(String(error?.message ?? error)); return; } this.socket.on('open', () => { opened = true; }); this.socket.on('message', (raw) => { let message; try { message = JSON.parse(raw.toString()); } catch { return; } const data = message.d ?? {}; if (message.op === 0) this.socket?.send(JSON.stringify({ op: 1, d: { rpcVersion: data.rpcVersion, authentication: this.auth(data.authentication), eventSubscriptions: METERS } })); else if (message.op === 2) { this.delay = 1_000; this.set({ ...offline(this.cfg), configured: true, connected: true, error: undefined }); this.request('GetInputList').then((v) => { this.sources = (v.inputs ?? []).map((input) => input.inputName).filter(Boolean); this.set({}); }).catch(() => {}); this.refresh().catch(() => {}); this.telemetry = setInterval(() => this.refresh().catch(() => {}), 1_000); this.telemetry.unref?.(); } else if (message.op === 5 && data.eventType === 'InputVolumeMeters') this.meter(data.eventData?.inputs ?? []); else if (message.op === 7) this.response(data); }); this.socket.on('error', (error) => { if (generation === this.generation) this.set({ error: String(error?.message ?? error) }); }); this.socket.on('close', () => { if (generation === this.generation) this.reconnectSoon(opened ? 'OBS connection lost. Reconnecting…' : 'OBS Studio could not be reached. Reconnecting…'); }); }
  async status({ force = false } = {}) { this.connect(); if (force) { const until = Date.now() + TIMEOUT; while (!this.current.connected && this.socket && Date.now() < until) await new Promise((resolve) => setTimeout(resolve, 50)); if (this.current.connected) await this.refresh(); } return this.current; }
}

function client(roomId) { const cfg = getObs(roomId); if (!cfg) { stop(roomId); return null; } const signature = JSON.stringify(cfg); const existing = clients.get(roomId); if (existing?.signature === signature) return existing; existing?.stop(); const next = new ObsClient(cfg); next.signature = signature; clients.set(roomId, next); return next; }
export async function status(roomId, options) { const current = client(roomId); return current ? current.status(options) : offline(null, 'Configure OBS Studio in this room’s Campus setup.'); }
export function inputs(roomId) { return clients.get(roomId)?.sources ?? []; }
export function stop(roomId) { const current = clients.get(roomId); current?.stop(); clients.delete(roomId); }
export function stopAll() { for (const roomId of [...clients.keys()]) stop(roomId); }
